# уникальный ключ проекта на сервере SonarQube
sonar.projectKey=DTL_CONF

# имя проекта на сервере SonarQube
sonar.projectName=\u0411\u0438\u0431\u043b\u0438\u043e\u0442\u0435\u043a\u0430\u0020\u0438\u043d\u0441\u0442\u0440\u0443\u043c\u0435\u043d\u0442\u043e\u0432\u0020\u0440\u0430\u0437\u0440\u0430\u0431\u043e\u0442\u043a\u0438

# версия исходников проекта
sonar.projectVersion=1.0

# Относительный путь к исходникам. Замените "\" на "/" при запуске на Windows.
# Если не указано, SonarQube будет искать исходный код начиная с каталога, содержащего файл sonar-project.properties.
sonar.sources=./src/main,./src/\u0411\u0438\u0431\u043b\u0438\u043e\u0442\u0435\u043a\u0430\u0418\u043d\u0441\u0442\u0440\u0443\u043c\u0435\u043d\u0442\u043e\u0432\u0420\u0430\u0437\u0440\u0430\u0431\u043e\u0442\u043a\u0438

# Относительный путь к тестам.
# sonar.tests=./tests

# тип системы контроля версий
sonar.scm.provider=git

# маска поиска файлов на проверку
sonar.inclusions=**/*.bsl,**/*.mdo,**/*.form,**/*.dcss,**/*.xml

# маска поиска исключений файлов на проверку
sonar.exclusions=**/*.html,**/Template.mxlx,**/Templates/**/*.mxlx,**/CommonPictures/**/*.*,**/Reports/\u0420\u0435\u0433\u043b\u0430\u043c\u0435\u043d\u0442\u0438\u0440\u043e\u0432\u0430\u043d\u043d*//*.*
sonar.lang.patterns.xml=**/*.xsd,**/*.xsl,**/*.mdo,**/*.form,**/*.dcss

# Кодировка исходного кода. По умолчанию используется системная кодировка.
sonar.sourceEncoding=UTF-8

sonar.ws.timeout=300
sonar.qualitygate.wait=false
sonar.qualitygate.timeout=300

# Путь к отчету о покрытии тестами
# sonar.coverageReportPaths=coverage/genericCoverage.xml

# Путь к отчету о выполнении тестов
# sonar.testExecutionReportPaths=test-reports/tests.xml